### ISSUE TITLE
Entrevista a Juan Manuel Barrera

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/actividad-2-entrevista-entrevista-metztli_team#2]
[Reporte de entrevista.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-entrevista-metztli_team/files/9491706/Reporte.de.entrevista.pdf)

**Comment by Yabin-2021** [comment]
Buen trabajo.
20% de calificación.

**Comment by josealfredo79** [comment]
Falto la síntesis de la entrevista....

**Comment by josealfredo79** [comment]
Favor de evaluar bien @Yabin-2021

**Comment by josealfredo79** [comment]
Calificación 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
